### ISSUE TITLE
NM="${TOOLCHAIN_BINDIR}"/usr/bin/ld

### ISSUE THREAD

**Issue by fedan** [NTULINUX/toolchain_builder#1]
Hi!
	AR="${TOOLCHAIN_BINDIR}"/usr/bin/ar \
	AS="${TOOLCHAIN_BINDIR}"/usr/bin/as \
	LD="${TOOLCHAIN_BINDIR}"/usr/bin/ld \
	NM="${TOOLCHAIN_BINDIR}"/usr/bin/nm \
	OBJCOPY="${TOOLCHAIN_BINDIR}"/usr/bin/objcopy \
	OBJDUMP="${TOOLCHAIN_BINDIR}"/usr/bin/objdump \
NM="${TOOLCHAIN_BINDIR}"/usr/bin/ld \

Is this how it should be?
NM="${TOOLCHAIN_BINDIR}"/usr/bin/ld \

**Comment by NTULINUX** [comment]
Sorry about that, dumb mistake, fixed now. Thanks for catching that! I've been working on my ARM64 rootfs builder, I haven't touched this in awhile.
